Algoritmo "Trabalho - Jogo Da Forca - Cuamba e Zavala - 1P1LDS1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Jogo da Forca
// Autor(a)    : Edilson Alexandre Cuamba - 2021101069
// Autor(a)    : Edilson Zavala
// Data atual  : 6/14/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Cuamba e Zavala")

Fimalgoritmo