/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package listaencadeada;

import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ListaSimplementeEncadeada<String> stringMyLinkedList = new ListaSimplementeEncadeada<>();
        JOptionPane.showMessageDialog(null, stringMyLinkedList.tamanho());
    }
}
