DROP DATABASE car_wash;

CREATE DATABASE car_wash;

USE car_wash;

CREATE TABLE pessoa(
	id BIGINT NOT NULL IDENTITY(1, 1),
	nome VARCHAR(255) NOT NULL,
	telefone VARCHAR(9) NULL,

	CONSTRAINT PK_PESSOA_ID PRIMARY KEY (id),
	INDEX INDEX_PESSOA_NOME(nome)
);

CREATE TABLE automovel(
	id BIGINT NOT NULL IDENTITY(1, 1),
	fabricante VARCHAR(255) NOT NULL,
	modelo VARCHAR(255) NOT NULL,
	matricula VARCHAR(255) NOT NULL,

	CONSTRAINT PK_AUTOMOVEL_ID PRIMARY KEY (id),
	CONSTRAINT UNIQUE_AUTOMOVEL_MATRICULA UNIQUE(matricula),
	INDEX INDEX_AUTOMOVEL_MATRICULA(matricula)
);

CREATE TABLE cliente(
	id BIGINT NOT NULL IDENTITY(1, 1),
	pessoa_id BIGINT NOT NULL,
	automovel_id BIGINT NULL,

	CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (id),
	CONSTRAINT FK_PESSOA_ID FOREIGN KEY (pessoa_id) REFERENCES pessoa(id),
	CONSTRAINT FK_AUTOMOVEL_ID FOREIGN KEY (automovel_id) REFERENCES automovel(id),
	CONSTRAINT UNIQUE_CLIENTE_PESSOA_ID_AUTOMOVEL_ID UNIQUE(pessoa_id, automovel_id)
);

CREATE TABLE factura(
	id BIGINT NOT NULL IDENTITY(1, 1),
	numero BIGINT NOT NULL,
	"data" DATE NOT NULL,
	total DECIMAL(12, 2) NOT NULL,
	cliente_id BIGINT NOT NULL,

	CONSTRAINT PK_FACTURA_ID PRIMARY KEY (id),
	CONSTRAINT FK_FACTURA_CLIENTE_ID FOREIGN KEY (cliente_id) REFERENCES cliente(id),
	CONSTRAINT UNIQUE_FACTURA_NUMERO UNIQUE(numero),
	INDEX INDEX_FACTURA_NUMERO(numero)
);

CREATE TABLE servico(
	id BIGINT NOT NULL IDENTITY(1, 1),
	nome VARCHAR(255) NOT NULL,
	preco DECIMAL(12, 2) NOT NULL,

	CONSTRAINT PK_SERVICO_ID PRIMARY KEY (id),
	INDEX INDEX_SERVICE_NOME(nome)
);

CREATE TABLE produto(
	id BIGINT NOT NULL IDENTITY(1, 1),
	nome VARCHAR(255) NOT NULL,
	preco DECIMAL(12, 2) NOT NULL,

	CONSTRAINT PK_PRODUTO_ID PRIMARY KEY (id),
	INDEX INDEX_PRODUTO_NOME(nome)
);

CREATE TABLE factura_item(
	id BIGINT NOT NULL IDENTITY(1, 1),
	factura_id BIGINT NOT NULL,
	servico_id BIGINT NULL,
	produto_id BIGINT NULL,
	quantodade BIGINT NULL,

	CONSTRAINT PK_FACTURA_ITEM_ID PRIMARY KEY (id),
	CONSTRAINT FK_FACTURA_ITEM_PESSOA_ID FOREIGN KEY (factura_id) REFERENCES factura(id),
	CONSTRAINT FK_FACTURA_ITEM_SERVICO_ID FOREIGN KEY (servico_id) REFERENCES servico(id),
	CONSTRAINT FK_FACTURA_ITEM_PRODUTO_ID FOREIGN KEY (produto_id) REFERENCES produto(id)
);

CREATE TABLE recibo(
	id BIGINT NOT NULL IDENTITY(1, 1),
	"data" DATE NOT NULL,
	total DECIMAL(12, 2) NOT NULL,

	CONSTRAINT PK_RECIBO_ID PRIMARY KEY (id)
);

CREATE TABLE recibo_factura(
	factura_id BIGINT NOT NULL,
	recibo_id BIGINT NOT NULL,

	CONSTRAINT FK_RECIBO_FACTURA_FACTURA_ID FOREIGN KEY (factura_id) REFERENCES factura(id),
	CONSTRAINT FK_RECIBO_FACTURA_RECIBO_ID FOREIGN KEY (recibo_id) REFERENCES recibo(id)
);




